Dashboard
Pudl0/westerloy pull request #1
Opened 2023-08-04 14:08 UTC by Pudl0

2023-08-04 20:44 UTC, Luminagitur commented
Wir müssen uns auch nochmal über Code Formatting auseinandersetzen, sodass wir dort dieselben Tools und Einstellungen nutzen. Ich denke mal du hast auch die Prettier Extension?

2023-08-04 21:14 UTC, Luminagitur commented
Die Elemente insgesamt wirken insgesamt etwas klein und wir haben den Platz. Der Platz rechts und links ist da. Ich würde das glaube ich bisschen größer machen. Was meinst Du?

2023-08-04 21:29 UTC, Luminagitur commented
Die Cards sehen top aus 💯

2023-08-04 21:30 UTC, Luminagitur requested changes
See comments

2023-08-04 21:30 UTC, Luminagitur commented on src/app/page.tsx
> +      <div className="lg:pt-32 md:pt-24 md:pb-12 pt-12 pb-12">
Hat das einen Grund, warum das Padding darüber und auch von dem Element darunter so hoch ist? Wirkt ziemlich leer dazwischen.

2023-08-07 07:14 UTC, Pudl0 commented on src/app/page.tsx
> +      <div className="lg:pt-32 md:pt-24 md:pb-12 pt-12 pb-12">
In Blazor hat das gepasst, ist mir aber auch schon als sehr groß aufgefallen.

2023-08-07 07:21 UTC, Pudl0 commented on src/components/ui/News-dashboard-item.tsx
> +                <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.
Die svg habe ich so von heroicons. Das fasse ich generell nicht an :D

2023-08-07 07:23 UTC, Pudl0 commented on src/app/page.tsx
> +import NewsDashboardItem from '@/components/ui/news-dashboard-item'
<newsDashboardItem /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    at newsDashboardItem

2023-08-07 07:24 UTC, Pudl0 commented on src/app/page.tsx
> +import NewsDashboardItem from '@/components/ui/news-dashboard-item'
FileName und Component können gar nicht die gleiche Convention einhalten, wenn React PascalCase erfordert. Wie siehst du das?

2023-08-07 07:29 UTC, Pudl0 commented on src/app/page.tsx
> +      <div className="lg:pt-32 md:pt-24 md:pb-12 pt-12 pb-12">
Ich wollte ursprünglich den Header mit dem Foto als "landing page" haben. Die Neuigkeiten sollten bewusst erst nach scrollen sichtbar sein. Hab das einfach runter geschoben.

2023-08-07 08:50 UTC, Luminagitur commented on src/app/page.tsx
> +import NewsDashboardItem from '@/components/ui/news-dashboard-item'
Ich glaube wir haben uns da falsch verstanden. War etwas schwammig von mir formuliert. Ich bezog mich bei dem Import auf das "N" in news, was klein geschrieben werden muss, da er sonst die File und die Component darin nicht finden kann. Der Import wäre sonst korrekt gewesen.

Wegen der Code Convention gibt es ein paar verschiedene Meinungen.
Ich orientiere mich an: "Kebab case for file names and Pascal case for component names."
React gibt natürlich für Components Pascal case vor, deswegen passt das und ist auch richtig so.

Also richtig ist:
- FileName: "news-dashboard-item.tsx"
- Component: "NewsDashboardItem"

Hier ist sonst noch ein Projekt, was mir ein gemeinsamer Kollege zugeschickt hat, woran ich mich auch dran orientiere.
Das Projekt nutzt auch die gleichen Conventions, wie oben beschrieben.
Ich denke, dass man React components und HTML elements ruhig mischen darf in eine Convention. Wüsste jetzt nicht warum man bei einem Pascal case und beim anderen Camel case machen sollte.

2023-08-07 08:58 UTC, Luminagitur requested changes

2023-08-07 08:58 UTC, Luminagitur commented on src/app/page.tsx
> +import NewsDashboardItem from '@/components/ui/newsDashboardItem'
see answer in comments

2023-08-07 09:03 UTC, Luminagitur requested changes

2023-08-07 09:03 UTC, Luminagitur commented on src/app/page.tsx
> +      <div className="lg:pt-32 md:pt-24 md:pb-12 pt-12 pb-12">
Dafür müsste das Image deutlich größer sein und ich müsste die navbar fertig bekommen, damit dieser Effekt wirken kann. Wollten die Components sowieso etwas größer machen, da es sonst sehr leer wirkt, gerade mit dem Padding auf der Horizontalen. Müssen wir uns sonst mal gemeinsam anschauen. Dann können wir die anderen Dinge auch abstimmen.

2023-08-15 09:36 UTC, Luminagitur approved these changes

2023-08-15 09:37 UTC, merged