Navbar
Pudl0/westerloy pull request #12
Opened 2023-09-12 20:18 UTC by Luminagitur

2023-09-13 08:35 UTC, Pudl0 requested changes
Casing sieht soweit ich das sehe gut aus. Habe ein paar Aufräum-Anmerkungen. Checke den Branch später aus und teste ob es gut funktioniert.

2023-09-13 08:35 UTC, Pudl0 commented on src/components/navbar.tsx
> +import { SidebarLink } from '@/lib/types/sidebar-link-types';
Bitte die imports sortieren => alle next untereinander, alle components usw...

2023-09-13 08:35 UTC, Pudl0 commented on src/components/navbar.tsx
> +      href: '#',
Warum haben die FlyoutItems keinen Link und die Sidebar Items in Zeile 91-94 schon?

2023-09-13 08:35 UTC, Pudl0 commented on src/components/ui/sheet.tsx
> +import { X } from 'lucide-react';
X ist mir zu kurz.

2023-09-13 08:36 UTC, Pudl0 commented on src/components/navbar.tsx
> +import { SidebarLink } from '@/lib/types/sidebar-link-types';
In allen files bitte überprüfen

2023-09-13 17:48 UTC, Luminagitur commented on src/components/navbar.tsx
> +      href: '#',
habe ich vergessen, upsi

2023-09-13 17:50 UTC, Luminagitur commented on src/components/ui/sheet.tsx
> +import { X } from 'lucide-react';
Ist tatsächlich standard durch den import der shadcn component.
@Pudl0 Was hätte der feine Herr denn gerne? ;)

2023-09-17 21:09 UTC, Pudl0 commented on src/components/ui/sheet.tsx
> +import { X } from 'lucide-react';
Was genau importierst du denn da?

2023-09-18 17:05 UTC, Luminagitur commented on src/components/ui/sheet.tsx
> +import { X } from 'lucide-react';
![image](https://github.com/Pudl0/westerloy/assets/84715441/fdcbd194-1f0d-46f8-a7a8-4d8998ddd921)

Das ist der "X"-Close-Button aus dem shadcn Sheet. Ist halt als const vordefiniert. Könnte dir soetwas in der Richtung anbieten:

![image](https://github.com/Pudl0/westerloy/assets/84715441/ffe27196-4815-4679-9d66-b04703bcbbb8)

2023-09-18 17:48 UTC, Pudl0 approved these changes

2023-09-18 17:48 UTC, merged