Evententry
Pudl0/westerloy pull request #3
Opened 2023-08-17 10:46 UTC by Pudl0

Die Background-Image Styles in der global.css sind sehr ähnlich. Da weiß ich grade keine Vereinfachung.

2023-08-17 21:41 UTC, finnholzgrabe commented on src/app/globals.css
> +    background-image: linear-gradient(180deg,transparent,rgba(0,0,0,.7));;
```suggestion
    background-image: linear-gradient(180deg, transparent, rgba(0, 0, 0, .7));
```

2023-08-17 21:42 UTC, finnholzgrabe commented on src/components/ui/event-dashboard-item.tsx
Als Filler gedacht?

2023-08-17 21:43 UTC, finnholzgrabe reviewed
Kleinigkeiten, aber eig. nix zu meckern, muss ich morgen mal auschecken

2023-08-18 07:05 UTC, Pudl0 commented on src/components/ui/event-dashboard-item.tsx
Ja, damit man gucken kann dass die Abstände in alle Richtungen passen usw.

2023-08-22 16:40 UTC, finnholzgrabe reviewed
Einmal meine Frage beantworten, sonst sieht das gut aus

2023-08-22 16:40 UTC, finnholzgrabe commented on src/components/cards/event-dashboard-item.tsx
> +              <svg
@Pudl0  Wieso bindest du nicht einfach fa icons ein?
Vereinheitlicht die UI und macht das ganze leserlicher, selbst hier würde ich die svgs auslagern und unter root/icons oder so unterbringen, besonders sowas wie `<i class="fa-solid fa-arrow-right"></i>`, bzw. das svg wird ja wiederverwendet werden.

2023-08-22 21:12 UTC, Luminagitur requested changes
See comments

2023-08-22 21:12 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
> +export default function EventDashboardItem() {
Ich habe das ganze noch etwas mehr responsive gemacht. So könnte das aussehen:
![EventDashboardItemExample](https://github.com/Pudl0/westerloy/assets/84715441/4fa84d59-d68d-4aae-b9be-a5222c488a0f)

Ich versuche mal die Änderungen stichpunktartig zusammenzufassen:
- Margin entfent, da die Margin nicht dazu genutzt werden sollte, um mehrere EventDashboardItems voneinander zu spacen, sondern besser durch `flex flex-col gap-y-[value]`
- Width angepasst, weshalb Padding auf der Page rausfällt. Weiß nicht, ob `xl:w-2/3` zu groß wirkt, muss ggf, angepasst werden. Hierzu sollte man bei großen Display eventuell dahin übergehen, dass man mehr Inhalt auf weniger Fläche hat, indem z.B. immer zwei Events in einer Row angezeigt werden. Wäre möglich durch Grid. Müsste dann aber sowieso auf der `page.tsx` geschehen.
- Textgrößen angepasst
- Svg ausgetauscht und angepasst (hier zukünftig evtl. FontAwesome nutzen => müssen wir mal abstimmen)

2023-08-22 21:15 UTC, finnholzgrabe commented on src/components/cards/event-dashboard-item.tsx
> +              <svg
Ja free reicht ja absolut, sind dann halt nur keine svgs, aber mit free kommt man schon dementsprechend weit

2023-08-22 21:17 UTC, finnholzgrabe commented on src/components/cards/event-dashboard-item.tsx
> +    <div className="flex flex-col mb-16 w-full bg-white rounded shadow-lg sm:w-3/4 md:w-1/2 lg:w-3/5">
Ich beschäftige mich schon mal mit angebrachten weiß und schwarz Tönen, würde dann tailwind auch einfach soweit modifizieren, dass wir die als default und custom mit reinschmeißen.
Können wir gerne gemeinsam die Tage festhalten 👍🏻

2023-08-23 06:54 UTC, Pudl0 commented on src/components/cards/event-dashboard-item.tsx
> +              <svg
Font Awesome benutzen wir tatsächlich beim Dashy Dashboard auf dem AzubiServer. Hatte aus Gewohnheit Heroicons genutzt. Ich schau mir FA gerne mal an und bau die Icons alle um.

2023-08-23 18:52 UTC, finnholzgrabe requested changes

2023-08-23 18:52 UTC, finnholzgrabe commented on src/components/cards/event-dashboard-item.tsx
> +            <FontAwesomeIcon icon={faLocationDot} className="fas fa-location-dot"></FontAwesomeIcon>
```suggestion
            <FontAwesomeIcon icon={faLocationDot}></FontAwesomeIcon>
```

2023-08-23 18:52 UTC, finnholzgrabe commented on src/components/cards/event-dashboard-item.tsx
> +  return (
Ich würde einfach den overflow hiden anstatt auch den content jeweils an top und bottom zu runden, oder hat das einen speziellen Grund, dass du das machst? Darf mMn. auch gerne etwas runder 
Ich hab jz nicht auf Philips Anmerkungen geachtet
```
    <div className="flex flex-col bg-white rounded-xl overflow-hidden drop-shadow-lg w-3/4 xl:w-2/3">
      <Image className="h-3/4 item-header" src="/Muehlenhof.jpg" width={1920} height={1080} alt="" />
      <div className="flex flex-col w-full md:flex-row">
        <div className="flex justify-around p-4 font-bold leading-none text-gray-800 uppercase bg-gray-300 md:flex-col md:items-center md:justify-center md:w-1/4">
          <div className="md:text-3xl xl:text-4xl">01.</div>
          <div className="md:text-lg xl:text-xl">Dezember</div>
          <div className="md:text-lg xl:text-xl">2021</div>
        </div>
        <div className="flex flex-col gap-y-2 p-4 font-normal text-gray-800">
          <h1 className="text-xl xl:text-2xl font-bold tracking-tight text-gray-800">Heimspiel 2. Herren</h1>
          <p className="leading-normal text-ms xl:text-lg">Wird wieder n mordsmäßiges Spiel</p>
          <div className="flex flex-row items-center text-gray-700 gap-2">
            <FontAwesomeIcon icon={faLocationDot}></FontAwesomeIcon>
            <div className="text-ms xl:text-lg">LVM Arena</div>
          </div>
        </div>
      </div>
    </div>
```

2023-08-23 18:52 UTC, finnholzgrabe commented on src/app/eventdashboard/page.tsx
> +    <main className="flex min-h-screen flex-col items-center justify-between gap-y-24">
```suggestion
    <main className="flex min-h-screen flex-col items-center justify-between gap-y-24 my-12">
```
Für Test gerne sowas, aber juckt

2023-08-23 19:10 UTC, finnholzgrabe approved these changes

2023-08-23 19:10 UTC, finnholzgrabe commented on src/components/news-detail-component.tsx
was removed by @Pudl0 anyways

2023-08-23 19:20 UTC, Luminagitur approved these changes
LGTM

2023-08-23 19:21 UTC, merged