Newsdatabase
Pudl0/westerloy pull request #4
Opened 2023-08-23 11:54 UTC by Pudl0

2023-08-26 21:07 UTC, finnholzgrabe approved these changes

2023-08-26 21:07 UTC, finnholzgrabe commented on src/app/newsdetail/[newsdetailid]/page.tsx
> +        <Image
Hier gibts noch ein resizing Issue, aber das muss woanders gefixt werden

2023-08-26 21:07 UTC, finnholzgrabe commented on src/components/cards/news-dashboard-item.tsx
> +import Link from 'next/link';
Reihenfolge mag ich nicht aber is fine

2023-08-28 06:47 UTC, Luminagitur requested changes
see comment

2023-08-28 06:47 UTC, Luminagitur commented on src/app/newsdetail/[newsdetailid]/page.tsx
> +import Image from 'next/image';
@Pudl0 Ich würde "id" in den eckigen Klammern groß schreiben, um das innerhalb des folder names abzuheben. Also: "[newsdtailId]". Was meinst Du?

2023-08-28 12:37 UTC, finnholzgrabe approved these changes

2023-08-29 07:58 UTC, merged