Eventdatabase
Pudl0/westerloy pull request #6
Opened 2023-08-29 10:56 UTC by Pudl0

2023-08-29 11:57 UTC, finnholzgrabe commented on prisma/schema.prisma
> -  TimeOfEvent DateTime @db.DateTime(0)
hat Prisma sich das falsch geholt, oder wie kam das jetzt?
Und läuft das mit oder ohne?

2023-08-29 13:09 UTC, Pudl0 commented on prisma/schema.prisma
> -  TimeOfEvent DateTime @db.DateTime(0)
Zieht der jedesmal automatisch. Läuft sowohl mit als auch ohne.

2023-08-29 20:20 UTC, Luminagitur requested changes
see comment

2023-08-29 20:20 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
> +export default function EventDashboardItem({ EventEntry }) {
- [ ] Binding element 'NewsEntry' implicitly has an 'any' type.ts(7031) 

@Pudl0 Schmeißt Dir deine IDE hier keinen Error? :o

2023-09-04 20:24 UTC, finnholzgrabe commented
Den muss einmal @Luminagitur regeln, dass ist absolut nicht mein Bier.
Aber bei mir lokal baut der auch nicht korrekt 🤔

2023-09-09 10:13 UTC, Luminagitur approved these changes
comments will be fixed in a future casing ticket
therefore LGTM

2023-09-09 10:13 UTC, Luminagitur commented on src/components/cards/news-dashboard-item.tsx
> +export default function NewsDashboardItem(props: { newsentry: NewsEntry }) {
Renaming-Ticket: parameter should be "newsEntry"

2023-09-09 10:13 UTC, Luminagitur commented on prisma/schema.prisma
> +model evententries {
Renaming-Ticket: model names should be pascal case

2023-09-09 10:13 UTC, Luminagitur commented on prisma/schema.prisma
> +model newsentries {
Renaming-Ticket: model names should be pascal case

2023-09-09 10:14 UTC, merged