49 check for shadcn navbar functionality
Pudl0/westerloy pull request #65
Opened 2024-06-16 18:34 UTC by Pudl0

2024-06-18 21:53 UTC, Luminagitur requested changes
- [ ] Menu-Button is placed incorrect on iPad and Mobile
![iPad and Mobile_Menu-Button_Incorrect Layout](https://github.com/Pudl0/westerloy/assets/84715441/0729fc88-af50-46d2-9690-a738d00e212e)

- [ ] Menu-Drawer does not close when navigation was done via any button
- [ ] Inconsistent fontSize
![Inconsistent fontSize](https://github.com/Pudl0/westerloy/assets/84715441/7bf8c538-18ef-434f-95f3-a0c452d45386)
- Maybe put some more space between icon and buttons inside navbar

2024-06-19 06:46 UTC, Pudl0 commented on src/components/navbar.tsx
> +                <SidebarLink name="Landjugend 3.0" href="/vereine/landjugend" icon={faPeopleGroup} />
This is a copy paste issue from the old side menu. The content of the side menu isn't complete either. I need to work an that.

2024-06-20 08:49 UTC, Pudl0 commented on src/components/navbar.tsx
> +                    <a className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md">
Für den Oberpunkt ist kein href vorgesehen.

2024-06-20 12:46 UTC, Pudl0 commented
Changes addresses, please review again.

2024-06-20 21:01 UTC, Luminagitur requested changes
Just one minor change...

Besides that, what do you think about separating logo and navigation elements little further?

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/2b2c3c82-6629-4d68-b659-e5fe49af01ff)

2024-06-20 21:15 UTC, Luminagitur commented
As an example:

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/9e8bca47-a784-4d17-8ab6-adc3da40b867)

2024-06-21 05:19 UTC, Pudl0 commented on src/components/navbar.tsx
> +import { faNewspaper } from '@fortawesome/free-regular-svg-icons';
Yes it should.  dont knwo why this did not get fixed by the linter.

2024-06-21 07:23 UTC, Pudl0 commented on src/components/navbar.tsx
> +import { faNewspaper } from '@fortawesome/free-regular-svg-icons';
@Luminagitur 
its not possible to change the navbar further without using padding. There is a div that gets added on runtime and its not w-full. The navbar is designed to adjust to the size needed so i built in pl and pr to the icon and the most left option to mess with the navbar max size. This looks good on large devices and on tablets and smaller it will render the sidebar anyways. This should be investigated though since its not acceptable long term.

2024-06-24 09:22 UTC, Luminagitur commented on src/components/navbar.tsx
> +import { faNewspaper } from '@fortawesome/free-regular-svg-icons';
okay, maybe u should even reorganize new navbar also with the muehlenhofIcon, as you applied styling in the component itself, so it is not reusable anymore... the styles should be available as a prop input, u know?
But u can do this in a follow-up issue, I dont wan't to block this pr any longer because of this :)

2024-06-24 09:24 UTC, Luminagitur approved these changes
LGTM, please do not forget creating the follow-up issue

2024-06-24 09:24 UTC, Luminagitur commented on src/components/muehelnhof-icon.tsx
> +    <Link href="/" className="lg:pr-48">
Missing styles input, so Component is not reusable, but you can do this in a follow-up issue, when u investigate the navbar problematics...

2024-06-24 11:40 UTC, merged