36 fix eventdashboarditem
Pudl0/westerloy pull request #66
Opened 2024-07-06 19:32 UTC by Pudl0

2024-07-09 20:49 UTC, Luminagitur requested changes
As we already discussed:
- There are many unnecessary stylings which have no effects and could be removed. We'll fix this together in a tiny refactoring :)
- I like the idea of using cards displaying event information using icons.
- There could be some screenshots which show out of scope problems. If so please tell me and create new issues.
- Some responsive things are missing, just have a look at the screenshots.

2024-07-09 20:49 UTC, Luminagitur commented on src/components/navbar.tsx
> +      <NavigationMenu className="bg-gray-100 max-lg:hidden">
Cropping behaviour is weird und "Zum Login" should not have a line break

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/a7f0b7c7-2771-4129-9cbf-39a89f4935d6)

2024-07-09 20:49 UTC, Luminagitur commented on src/components/navbar.tsx
Color inconsistency looks weird, maybe some color or do we have some other options?
Related code should be in line 89.

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/728bbe3c-cdf7-4141-a718-e19819063d3d)

2024-07-09 20:49 UTC, Luminagitur commented on src/app/page.tsx
You have many margins and paddings in your child components, which should be specfied in the parent component as you will loose the overview, where stylings are applied. This is noticable in the following example, where distance between these sections are inconsistent as the upper distance is bigger than bottom one,

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/0844654c-299d-448c-a1fe-dbe76103cfd5)

2024-07-09 20:49 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
Truncating problem

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/83c3d1a0-2c0b-4720-b8fc-5906272ebea1)

2024-07-09 20:49 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
Why leaving out description already below width of 1279px? Even on mobile I'd suggest having the description shown. On mobile you could truncate very early, make the dashboard item clickable which then routes to a event-detail route like `https://westerloy.de/events/id`, where the event is fully shown. Or make the the truncating clickable, so only some lines are shown and rest of description will be shown, if you click on the event, but therefore I'd suggest to use a button, so users can notice this functionality.

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/4f78450b-b933-4337-b9cf-4abc975bc430)

2024-07-09 20:49 UTC, Luminagitur commented on src/app/page.tsx
Yeah, this is what I meant by loosing overview of stylings :D
A smaller width forces even more inconsistent stylings, which represents the opposite of the situation before.

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/f6643a56-1c7d-4328-8d61-88e3bf02c257)

2024-07-09 20:49 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
Pretty much space for barely content IMHO. Maybe consider making cards wider gaps between events a little shorter. Furthermore title looks pretty big for devices between a width of 768 and 1024px.

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/28ee52d3-9267-468b-8998-05ef2689f9d8)

2024-07-09 20:49 UTC, Luminagitur commented on src/app/page.tsx
Again pretty much space for barely content IMHO as well as title is a little too big and card should be wider. For refernce: This is a screenshot of an iPhone 13 Pro Max.

![grafik](https://github.com/Pudl0/westerloy/assets/84715441/0896faba-be52-4514-920e-b27eec2edb47)

2024-07-10 08:15 UTC, Pudl0 commented on src/components/navbar.tsx
I will adress this in https://github.com/Pudl0/westerloy/issues/71

2024-07-10 08:16 UTC, Pudl0 commented on src/components/navbar.tsx
> +      <NavigationMenu className="bg-gray-100 max-lg:hidden">
I will adress this in https://github.com/Pudl0/westerloy/issues/71

2024-07-10 08:23 UTC, Pudl0 commented on src/app/page.tsx
This will get addressed in https://github.com/Pudl0/westerloy/issues/72

2024-07-10 08:23 UTC, Pudl0 commented
@Luminagitur I linked 3 new tickets for the newsDashboard and navbar related stuff. I resolved the conversation for them. All the Eventstuff will be fixed in this ticket.

2024-07-10 13:54 UTC, Luminagitur commented on src/components/navbar.tsx
> +      <NavigationMenu className="bg-gray-100 max-lg:hidden">
- [ ] You forgot to mention the weird cropping behaviour and line break for "Zum Login" in the new issue #71.

2024-07-10 13:59 UTC, Luminagitur commented on src/components/cards/event-dashboard-item.tsx
@Pudl0 
Are you aware that this problem appears in EventDashboardItem? I don't know if it also exists for NewsDashboardItems 😅

2024-07-11 10:12 UTC, Pudl0 commented on src/components/navbar.tsx
> +      <NavigationMenu className="bg-gray-100 max-lg:hidden">
specific issues now mentioned.

2024-07-11 10:18 UTC, Pudl0 commented on src/components/cards/event-dashboard-item.tsx
@Luminagitur the non clickable EventItems are a specific request by the stakeholders since they fear too much complexity for older users which may be the majority. I left out the description since it is optional most of the time. At the very beginning I added a Detailspage for Events like with News but it got requested to remove it early in development. What do you think about a modal window that pops up after clicking the item and leaving the description out on every screen size?

2024-07-11 19:15 UTC, Luminagitur approved these changes
LGTM

2024-07-11 19:15 UTC, merged