54 add dummy data seeding for dev experience
Pudl0/westerloy pull request #67
Opened 2024-07-08 05:35 UTC by Pudl0

2024-07-08 22:25 UTC, Luminagitur requested changes
see comments

2024-07-08 22:25 UTC, Luminagitur commented on package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/dev-seed.ts"
2 steps as I had problems running prisma db seed script:

1. You need to install tsconfig-paths as dev dependency: `npm install tsconfig-paths --save-dev` .
2. Change seed script to `ts-node -r tsconfig-paths/register --compiler-options {\"module\":\"CommonJS\"} prisma/dev-seed.ts` .

Problem:
`Error: Cannot find module '@/lib/utils/dummy-data-constants'`

This is due to ts-node not knowing the tsconfig file. If you're running your TypeScript files with ts-node, you can use the tsconfig-paths package to enable ts-node to respect the paths configuration in `tsconfig.json.`

2024-07-08 22:25 UTC, Luminagitur commented on prisma/dev-seed.ts
## Suggestion

There is a nice package, which automatically generates randomized data for multiple use cases, so every entry would be unique.

- NPM Package: https://www.npmjs.com/package/chance
- Documentation: https://chancejs.com/

Required work for implementing this is low, maybe u have a look at this.
If you prefer not to change your code, that's fine with me :)

### `dummy-data.ts` in `./src/lib/prisma/dummy-data/dummy-data.ts`
![grafik](https://github.com/Pudl0/westerloy/assets/84715441/5c7c7422-7000-4c5a-b1f9-d18e24142967)

### `seed-dev.ts` in `./prisma/seed-dev.ts`
![grafik](https://github.com/Pudl0/westerloy/assets/84715441/4e2560eb-d409-412d-ab10-0d591dc0061d)

2024-07-08 22:25 UTC, Luminagitur commented on src/lib/utils/dummy-data-constants.ts
If you prefer my suggestion, I would delete this file.

2024-07-09 09:16 UTC, Pudl0 commented on README.md
applying suggested readme

2024-07-09 09:17 UTC, Pudl0 commented on package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/dev-seed.ts"
Added dependency

2024-07-09 09:17 UTC, Pudl0 commented on prisma/dev-seed.ts
suggestion implemented. Chance looks great and worked out of the box.

2024-07-09 10:06 UTC, Luminagitur requested changes
see comments

2024-07-09 10:06 UTC, Luminagitur commented on prisma/dummy-data.ts
> +        where: { id: 0 },
Why `where: { id: 0 }` ? 

Prisma will look up if an event with id 0 already exists. If not it will create an event.
As this is only test data, which has no hard relations like an deleted user or event id, I'd suggest to use `.create()` instead of `.upsert` .

2024-07-09 10:06 UTC, Luminagitur commented on prisma/dummy-data.ts
> +        where: { id: 0 },
same as above

2024-07-09 10:47 UTC, Pudl0 commented on prisma/dummy-data.ts
> +        where: { id: 0 },
I followed the prisma guide so i chose upsert instead of create. Your suggestion makes sense and i changed it since we have no reason to keep upsert.

2024-07-09 14:50 UTC, Luminagitur requested changes
see comments

2024-07-09 14:50 UTC, Luminagitur commented on prisma/dev-seed.ts
> +const prisma = new PrismaClient();
Unnecessary use of prisma instance, should be removed as well as the disconnects.

2024-07-09 14:50 UTC, Luminagitur commented on prisma/dev-seed.ts
> +async function main() {
Remove main and just use `dummData.seed().then()...` directly.
Don't forget to add console.log() for successful seeding.

Like my suggestion I gave in first review:
![image](https://github.com/Pudl0/westerloy/assets/84715441/5a79cc8c-0891-4657-a82d-a6f13b38a4b0)

2024-07-09 19:51 UTC, Luminagitur approved these changes
LGTM :)

2024-07-09 19:51 UTC, merged